################################# 模型配置参数 #################################
# pose模型的相关配置文件的地址
POSE_CONFIGS_PATH:
    IPOSE/configs/PoseConfigs/litehrnet_18_coco_odn_256×192.py
# pose模型的参数文件的位置
POSE_CHECKPOINT_PATH:
    IPOSE/weights/epoch_210.pth
################################# 输入输出配置参数 #################################
# image的根目录
IMAGE_ROOT_PATH:
    IPOSE/InputImage/sample.jpg
# 是否可视化图片
SHOW_IMAGE:
    False

# 输出文件的根目录
OUTPUT_IMAGE_ROOT_PATH:
    IPOSE/ResImage/sample.jpg

################################# 其他参数 #################################

# 使用的设备 Device used for inference
DEVICE:
    CUDA:0
# Keypoint score threshold
KEYPOINT_SCORE_THRESHOLD:
    0.3
# Keypoint radius for visualization
REDIUS:
    15
# Link thickness for visualization
THICKNESS:
    10
