################################# 模型配置参数 #################################
# pose模型的相关配置文件的地址
POSE_CONFIGS_PATH:
    BackEndTools\configs\PoseConfigs\litehrnet_30_coco_odn_384x288.py
# pose模型的参数文件的位置
POSE_CHECKPOINT_PATH:
    BackEndTools\weights\litehrnet_30_coco_odn_384x288.pth
################################# 输入输出配置参数 #################################
# image的根目录
IMAGE_ROOT_PATH:
    BackEndTools\InputImage\sample.jpg
# 是否可视化图片
SHOW_IMAGE:
    False

# 输出文件的根目录
OUTPUT_IMAGE_ROOT_PATH:
    ResImage\sample.jpg

################################# 其他参数 #################################

# 使用的设备 Device used for inference
DEVICE:
    CPU
# Keypoint score threshold
KEYPOINT_SCORE_THRESHOLD:
    0.3
# Keypoint radius for visualization
REDIUS:
    15
# Link thickness for visualization
THICKNESS:
    10

